package on2012_08.on2012_7_23.twoconvexshapes;

import net.egork.chelper.tester.TopCoderTester;
import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!TopCoderTester.test("int countWays(String[] grid)",
			"on2012_08.on2012_7_23.twoconvexshapes.TwoConvexShapes",
			"??,??;;14;;true::B?,??;;7;;true::WWB,WWW,WWW,WWW;;1;;true::BBBBBB,WWBBBB,WBBBBB;;0;;true::?BB?,BBBB,?BB?;;5;;true::?WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW,B?WWWWWWWWWWWWWWWWWWWWWWWWWWWWW,BB?WWWWWWWWWWWWWWWWWWWWWWWWWWWW,BBB?WWWWWWWWWWWWWWWWWWWWWWWWWWW,BBBB?WWWWWWWWWWWWWWWWWWWWWWWWWW,BBBBB?WWWWWWWWWWWWWWWWWWWWWWWWW,BBBBBB?WWWWWWWWWWWWWWWWWWWWWWWW,BBBBBBB?WWWWWWWWWWWWWWWWWWWWWWW,BBBBBBBB?WWWWWWWWWWWWWWWWWWWWWW,BBBBBBBBB?WWWWWWWWWWWWWWWWWWWWW,BBBBBBBBBB?WWWWWWWWWWWWWWWWWWWW,BBBBBBBBBBB?WWWWWWWWWWWWWWWWWWW,BBBBBBBBBBBB?WWWWWWWWWWWWWWWWWW,BBBBBBBBBBBBB?WWWWWWWWWWWWWWWWW,BBBBBBBBBBBBBB?WWWWWWWWWWWWWWWW,BBBBBBBBBBBBBBB?WWWWWWWWWWWWWWW,BBBBBBBBBBBBBBBB?WWWWWWWWWWWWWW,BBBBBBBBBBBBBBBBB?WWWWWWWWWWWWW,BBBBBBBBBBBBBBBBBB?WWWWWWWWWWWW,BBBBBBBBBBBBBBBBBBB?WWWWWWWWWWW,BBBBBBBBBBBBBBBBBBBB?WWWWWWWWWW,BBBBBBBBBBBBBBBBBBBBB?WWWWWWWWW,BBBBBBBBBBBBBBBBBBBBBB?WWWWWWWW,BBBBBBBBBBBBBBBBBBBBBBB?WWWWWWW,BBBBBBBBBBBBBBBBBBBBBBBB?WWWWWW,BBBBBBBBBBBBBBBBBBBBBBBBB?WWWWW,BBBBBBBBBBBBBBBBBBBBBBBBBB?WWWW,BBBBBBBBBBBBBBBBBBBBBBBBBBB?WWW,BBBBBBBBBBBBBBBBBBBBBBBBBBBB?WW,BBBBBBBBBBBBBBBBBBBBBBBBBBBBB?W;;73741817;;true"))
		{
			Assert.fail();
		}
	}
}
